<a href="https://colab.research.google.com/github/Blusooyeon/bigdata-analysist-certificate/blob/main/T2_house_sales_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
#데이터 로드
x_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/kingcountyprice/x_train.csv")
y_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/kingcountyprice/y_train.csv")
x_test= pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/kingcountyprice/x_test.csv")

display(x_train.head())
display(y_train.head())

,ID,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2,8651400730,20150428T000000,3,1.00,840,5525,1.0,0,0,...,6,840,0,1969,0,98042,47.3607,-122.085,920,5330
1,3,3163600130,20150317T000000,3,1.00,1250,8000,1.0,0,0,...,7,1250,0,1956,0,98146,47.5065,-122.337,1040,6973
2,4,5045700330,20140725T000000,4,2.50,2200,6400,2.0,0,0,...,8,2200,0,2010,0,98059,47.4856,-122.156,2600,5870
3,5,1036100130,20140808T000000,3,2.50,1980,39932,2.0,0,0,...,8,1980,0,1994,0,98011,47.7433,-122.196,2610,12769
4,6,7696630080,20140506T000000,3,1.75,1690,7735,1.0,0,0,...,7,1060,630,1976,0,98001,47.3324,-122.280,1580,7503

   ID     price
0   2  191000.0
1   3  234900.0
2   4  460000.0
3   5  442000.0
4   6  197000.0

In [2]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17290 entries, 0 to 17289
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             17290 non-null  int64
 1   id             17290 non-null  int64
 2   date           17290 non-null  object
 3   bedrooms       17290 non-null  int64
 4   bathrooms      17290 non-null  float64
 5   sqft_living    17290 non-null  int64
 6   sqft_lot       17290 non-null  int64
 7   floors         17290 non-null  float64
 8   waterfront     17290 non-null  int64
 9   view           17290 non-null  int64
 10  condition      17290 non-null  int64
 11  grade          17290 non-null  int64
 12  sqft_above     17290 non-null  int64
 13  sqft_basement  17290 non-null  int64
 14  yr_built       17290 non-null  int64
 15  yr_renovated   17290 non-null  int64
 16  zipcode        17290 non-null  int64
 17  lat            17290 non-null  float64
 18  long           17290 non-null  float64
 19  sqft_living15  17290 non-null  int64
 20  sqft_lot15     17290 non-null  int64
dtypes: float64(4), int64(16), object(1)
memory usage: 2.8+ MB

In [3]:
x_train.isnull().sum()

ID               0
id               0
date             0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [4]:
x_train.nunique(

)

ID               17290
id               17175
date               369
bedrooms            13
bathrooms           30
sqft_living        933
sqft_lot          8443
floors               6
waterfront           2
view                 5
condition            5
grade               12
sqft_above         852
sqft_basement      284
yr_built           116
yr_renovated        68
zipcode             70
lat               4827
long               727
sqft_living15      715
sqft_lot15        7492
dtype: int64

In [5]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error , mean_absolute_error , mean_absolute_percentage_error ,r2_score
import numpy as np

In [8]:
drop_col = ['ID','id','sqft_living','sqft_lot','sqft_above','sqft_basement','lat','long','sqft_living15','sqft_lot15']
x_train_drop = x_train.drop(columns = drop_col)
x_test_drop = x_test.drop(columns = drop_col)
y_train_target = y_train['price']

In [11]:

combined = pd.concat([x_train_drop, x_test_drop])
combined_encoded = pd.get_dummies(combined)
train_encoded = combined_encoded[:len(x_train_drop)]
test_encoded = combined_encoded[len(x_train_drop):]

xtr , xt , ytr, yt = train_test_split(train_encoded , y_train_target)

rf = RandomForestRegressor(random_state =42)
rf.fit(xtr,ytr)

y_validation_pred = rf.predict(xt)

In [12]:
#mse
print('validation mse' ,mean_squared_error(yt,y_validation_pred))

#mae
print('validation mae' ,mean_absolute_error(yt,y_validation_pred))

#mape
print('validation mape' ,mean_absolute_percentage_error(yt,y_validation_pred))

#rmse
print('validation rmse' ,np.sqrt(mean_absolute_percentage_error(yt,y_validation_pred)))

#r2
print('validation r2 score' ,r2_score(yt,y_validation_pred))

validation mse 31449091005.665405
validation mae 98317.2313741284
validation mape 0.17988484657391718
validation rmse 0.4241283373861232
validation r2 score 0.7621499975068426